import fs from 'fs';
import path from 'path';

const API_URL = 'https://marchellothejeweler.com/products.json?limit=250';

async function fetchProducts() {
  console.log('Fetching products from:', API_URL);
  const response = await fetch(API_URL);
  const data = await response.json();
  return data.products || [];
}

function escapeSql(str) {
  if (!str) return '';
  return str.replace(/'/g, "''");
}

async function generateSeed() {
  const products = await fetchProducts();
  console.log(`Found ${products.length} products. Generating seed.sql...`);

  let sql = `-- Seed file generated by scrape.js\n`;
  sql += `-- Instructions: Copy and paste this into your Supabase SQL Editor to insert products.\n\n`;

  for (const p of products) {
    const name = escapeSql(p.title);
    const slug = escapeSql(p.handle);
    const description = escapeSql(p.body_html || p.title);
    
    // Attempt to parse price from variants
    let price = 0;
    if (p.variants && p.variants.length > 0) {
      price = parseFloat(p.variants[0].price) || 0;
    }

    // Extract images
    const images = (p.images || []).map(img => img.src);
    const imagesJson = escapeSql(JSON.stringify(images));

    // For products, category_id is usually a UUID. Since we don't know the categories, we can set it to NULL
    // or leave it out if it has a default, but since it's an FK, NULL is safe.
    
    sql += `INSERT INTO public.products (name, slug, description, price, images, is_published, stock)\n`;
    sql += `VALUES ('${name}', '${slug}', '${description}', ${price}, '${imagesJson}'::jsonb, true, 10)\n`;
    sql += `ON CONFLICT (slug) DO UPDATE SET\n`;
    sql += `  name = EXCLUDED.name,\n`;
    sql += `  description = EXCLUDED.description,\n`;
    sql += `  price = EXCLUDED.price,\n`;
    sql += `  images = EXCLUDED.images;\n\n`;
  }

  const outPath = path.join(process.cwd(), 'supabase', 'seed.sql');
  fs.writeFileSync(outPath, sql, 'utf8');
  console.log(`Successfully wrote ${products.length} products to supabase/seed.sql`);
}

generateSeed().catch(err => {
  console.error("Error generating seed:", err);
});
