import fs from 'fs';
import path from 'path';

const API_URL = 'https://marchellothejeweler.com/products.json?limit=250';

async function fetchProducts() {
  console.log('Fetching products from:', API_URL);
  const response = await fetch(API_URL);
  const data = await response.json();
  return data.products || [];
}

function escapeSql(str) {
  if (!str) return '';
  if (typeof str !== 'string') str = String(str);
  return str.replace(/'/g, "''");
}

async function generateSeed() {
  const products = await fetchProducts();
  console.log(`Found ${products.length} products. Generating seed.sql...`);

  let sql = `-- Seed file generated by scrape.js\n`;
  sql += `-- Instructions: Copy and paste this into your Supabase SQL Editor to insert products.\n\n`;

  const CATEGORIES = [
    { id: '11111111-1111-1111-1111-111111111111', slug: 'rings', name: 'Rings', sort_order: 1 },
    { id: '22222222-2222-2222-2222-222222222222', slug: 'earrings', name: 'Earrings', sort_order: 2 },
    { id: '33333333-3333-3333-3333-333333333333', slug: 'pendants', name: 'Pendants', sort_order: 3 },
    { id: '44444444-4444-4444-4444-444444444444', slug: 'chains', name: 'Chains', sort_order: 4 },
    { id: '55555555-5555-5555-5555-555555555555', slug: 'watches', name: 'Watches', sort_order: 5 },
    { id: '66666666-6666-6666-6666-666666666666', slug: 'bracelets', name: 'Bracelets', sort_order: 6 },
  ];

  for (const c of CATEGORIES) {
    sql += `INSERT INTO public.categories (id, slug, name, sort_order) VALUES ('${c.id}', '${c.slug}', '${c.name}', ${c.sort_order}) ON CONFLICT (slug) DO UPDATE SET name = EXCLUDED.name, sort_order = EXCLUDED.sort_order;\n`;
  }
  sql += `\n`;

  for (const p of products) {
    const name = escapeSql(p.title);
    const slug = escapeSql(p.handle);
    const description = escapeSql(p.body_html || p.title);
    
    // Attempt to parse price from variants
    let price = 0;
    if (p.variants && p.variants.length > 0) {
      price = parseFloat(p.variants[0].price) || 0;
    }

    // Extract images
    const images = (p.images || []).map(img => img.src);
    const imagesJson = escapeSql(JSON.stringify(images));

    // SEO Data
    const focusKeyphrase = name;
    const seoTitle = escapeSql(`${p.title} | Lumina Luxe Jewels`);
    const plainDescription = p.body_html ? p.body_html.replace(/<[^>]+>/g, '').trim() : p.title;
    const seoMetaDescription = escapeSql(plainDescription.substring(0, 160));
    const tags = p.tags ? escapeSql(p.tags) : '';

    const lowerType = (p.product_type || '').toLowerCase();
    const lowerTags = tags.toLowerCase();
    const lowerTitle = p.title.toLowerCase();
    
    let categoryId = 'NULL';
    if (lowerType.includes('ring') || lowerTags.includes('ring') || lowerTitle.includes('ring')) categoryId = `'11111111-1111-1111-1111-111111111111'`;
    else if (lowerType.includes('earring') || lowerTags.includes('earring') || lowerTitle.includes('earring')) categoryId = `'22222222-2222-2222-2222-222222222222'`;
    else if (lowerType.includes('pendant') || lowerTags.includes('pendant') || lowerTitle.includes('pendant') || lowerType.includes('cross') || lowerTags.includes('cross')) categoryId = `'33333333-3333-3333-3333-333333333333'`;
    else if (lowerType.includes('chain') || lowerTags.includes('chain') || lowerTitle.includes('chain') || lowerTitle.includes('necklace')) categoryId = `'44444444-4444-4444-4444-444444444444'`;
    else if (lowerType.includes('watch') || lowerTags.includes('watch') || lowerTitle.includes('rolex') || lowerTitle.includes('audemars')) categoryId = `'55555555-5555-5555-5555-555555555555'`;
    else if (lowerType.includes('bracelet') || lowerTags.includes('bracelet') || lowerTitle.includes('bracelet')) categoryId = `'66666666-6666-6666-6666-666666666666'`;

    sql += `INSERT INTO public.products (name, slug, description, price, images, is_published, stock, focus_keyphrase, seo_title, seo_meta_description, tags, category_id)\n`;
    sql += `VALUES ('${name}', '${slug}', '${description}', ${price}, '${imagesJson}'::jsonb, true, 10, '${focusKeyphrase}', '${seoTitle}', '${seoMetaDescription}', '${tags}', ${categoryId})\n`;
    sql += `ON CONFLICT (slug) DO UPDATE SET\n`;
    sql += `  name = EXCLUDED.name,\n`;
    sql += `  description = EXCLUDED.description,\n`;
    sql += `  price = EXCLUDED.price,\n`;
    sql += `  images = EXCLUDED.images,\n`;
    sql += `  focus_keyphrase = EXCLUDED.focus_keyphrase,\n`;
    sql += `  seo_title = EXCLUDED.seo_title,\n`;
    sql += `  seo_meta_description = EXCLUDED.seo_meta_description,\n`;
    sql += `  tags = EXCLUDED.tags,\n`;
    sql += `  category_id = EXCLUDED.category_id;\n\n`;
  }

  const outPath = path.join(process.cwd(), 'supabase', 'seed.sql');
  fs.writeFileSync(outPath, sql, 'utf8');
  console.log(`Successfully wrote ${products.length} products to supabase/seed.sql`);
}

generateSeed().catch(err => {
  console.error("Error generating seed:", err);
});
